name: PluginLite
version: 1.0
main: fr.miitnt.pluginlite.Pluginlite
api-version: 1.16
authors: [ MiiTnT ]
description: PluginLite permet de cacher certaines informations au joueurs
website: www.multiffa.fun
commands:
  gm:
    description: Simple commande pour changer de gamemode
    aliases: [gms, gma, gmc, gmsp]
  litereload:
    description: Reload PluginLite
    permission: pluginlite.time.reload
  day:
    description: Mettre le jour
    permission: pluginlite.time.day
  night:
    description: Mettre la nuit
    permission: pluginlite.time.night
  sun:
    description: Mettre le beau temp
    permission: pluginlite.time.sun
  rain:
    description: Mettre le mauvais temp
    permission: pluginlite.time.rain
  craft:
    description: Ouvrir une table de craft
    permission: pluginlite.craft
  furnace:
    description: Ouvrir un four
    permission: pluginlite.furnace
  setservername:
    description: SerServerName
    permission: pluginlite.servername
